# Generated by Django 5.0.1 on 2024-01-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_favorite_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
